# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfNVneSKKq0w7_seNWglmGsl6m2e2KhX
"""

import streamlit as st
import pandas as pd

st.title("🏡 Residential Plot Finder")

# File uploader
uploaded_file = st.file_uploader("📂 Upload Excel file with plot data", type=["csv"])

if uploaded_file:
    # Read Excel file
    df = pd.read_csv(uploaded_file)

    # Clean column names for safety
    df.columns = df.columns.str.strip()

    # Ask for client budget
    budget = st.number_input("💰 Enter Client's Investment Budget (INR)", min_value=0)

    if budget > 0:
        # Filter: Only available plots under budget
        filtered_df = df[
            (df['Status'].str.lower() != 'sold out') &
            (df['9 % Pricing Discount Rates ( 1350 * 810 )'] <= budget)
        ]

        num_available = filtered_df.shape[0]

        st.markdown(f"### ✅ {num_available} Plot(s) Available Within Budget")

        if num_available > 0:
            st.dataframe(filtered_df[['NO',
                                      'TOTAL PLOT AREA IN SQ. FEET',
                                      'RATE (1500)*(900)',
                                      '9 % Pricing Discount Rates ( 1350 * 810 )',
                                      'Status']])
        else:
            st.warning("❌ No plots available in this budget.")
else:
    st.info("👆 Please upload your Excel file to begin.")
